<div class="section" lang="en" xml:lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both"><a id="ch04lvl1sec32"></a>Catching errors in Koa</h2></div></div><hr /></div><p>One of the great things about error handling in Koa is that, by default, the framework handles all errors, either asynchronous or synchronous. This is made <span>possible</span><a id="id325850722" class="indexterm"></a> by the fact that Koa has a cascading middleware stack and an error handler can be added at the very top of the stack, which will unwind last. This <span>makes</span><a id="id325850726" class="indexterm"></a> it possible for Koa to handle all uncaught errors in applications by default.</p><p>Koa's default behavior is to output all errors to stderr unless <code class="literal">app.silent</code> is set to <code class="literal">true</code>.</p><p>To catch errors that occur in Koa, you can define an error-handling middleware to run as one of the first middleware. This is in contrast to Express, where error-handling middleware has to be defined as the last in the stack, with the signature <code class="literal">(err, req, res, next)</code>.</p><p>In Koa, error-handling middleware can be defined as any other middleware, with the notable exception that it has to be registered as one of the first middleware. This ensures that the handler catches all errors in subsequent middleware.</p><p>A simple handler can be defined as seen as follows:</p><pre class="programlisting">// catch all error in preceding middleware
app.use(async (ctx, next) =&gt; {
  try {
    await next();
  } catch(err) {
    ctx.status = err.status || 500;
    ctx.body = err.message;
  }
});

// throw error in response middleware
app.use(async ctx =&gt; {
  throw new Error('An error occurred');
  ctx.body = 'Hello, world';
});</pre><p> </p><p> </p><p> </p><p> </p><p>In the code block, first, we define and register a middleware that wraps the call to the next <code class="literal">middleware</code> function in a <code class="literal">try</code> block. Hence, all errors that are thrown in <span>subsequent</span><a id="id325913489" class="indexterm"></a> middleware <span>cascade</span><a id="id325913472" class="indexterm"></a> up and will flow into the corresponding <code class="literal">catch</code> block.</p><p>Running the preceding code in a Koa app and visiting any route in the app will write a text response back to the client with the <code class="literal">An error occurred</code> message: </p><pre class="programlisting">curl http://localhost:1234

// =&gt; An error occurred</pre><p>Koa makes it possible to use simple <code class="literal">try... catch</code> statements for error handling, unlike in Express where the error in asynchronous functions has to be explicitly passed to the next middleware, using the <code class="literal">next()</code> method.</p><p>Errors can also be caught and transformed by implementing error-handling middleware. This is particularly useful for transforming errors of a particular kind and can help to reduce multiple <code class="literal">try... catch</code> statements. Here is an example of this use case:</p><pre class="programlisting">app.use(async (ctx, next) =&gt; {
  try {
    await next();
  } catch(err) {
    if (err.status === 409 || err.statusCode === 409) {
      err.message = "Conflict with current data exists!"
    }
    throw err;
  }
});</pre><p>In the preceding example, the <span>error</span><a id="id325859275" class="indexterm"></a> is modified and <span>throw</span><a id="id325859284" class="indexterm"></a> again to be handled by Koa's default response handler.</p><p> </p><div class="section" lang="en" xml:lang="en"><div class="titlepage"><div><div><h3 class="title"><a id="ch04lvl2sec17"></a>Koa's default error handler</h3></div></div></div><p>Koa implements a default error handler, which <span>works</span><a id="id325903232" class="indexterm"></a> well for <span>many</span><a id="id325903240" class="indexterm"></a> situations. It is essentially middleware with a <code class="literal">try...catch</code> statement defined at the very top of the Koa middleware stack. If no other error handler is defined, all errors thrown when the application is running will flow into Koa's default error handler.</p><p>The default handler uses the status code of <code class="literal">err.status</code> when available, else it uses <code class="literal">500</code> (for <code class="literal">Internal Server Error</code>). It also sends back <code class="literal">err.message</code> as the response if <code class="literal">err.expose</code> is set to <code class="literal">true</code>.</p><p> </p><p> </p><p>If <code class="literal">err.expose</code> is set to <code class="literal">false</code>, then it generates a message from the error code of the error thrown. For exa<span>mple, for t</span>he <code class="literal">400 Bad Request error</code>, the message generated will be <code class="literal">Invalid Request</code>.</p><p>When sending back a response, the default error handler clears all headers, except for the ones present in <code class="literal">err.headers</code>. We can set headers for errors using a <code class="literal">try... catch</code> statement in another middleware, as seen here:</p><pre class="programlisting">app.use(async (ctx, next) =&gt; {
  try {
    await next();
  } catch(err) {
    if (err.status === 503) {
      err.headers = Object.assign({}, err.headers, {
        'Retry-After': 30
      });
    }

    throw err;
  }
});</pre><p>The preceding code shows how we set the <code class="literal">Retry-After</code> header value for <code class="literal">503 Service Unavailable</code> errors.</p><p>When an error occurs, and it is still possible to <span>respond</span><a id="id325913476" class="indexterm"></a> back to the client (no data has been written to the socket), as expected, Koa responds with <code class="literal">500 Internal Server Error</code>. Either way, the error <span>event</span><a id="id325913504" class="indexterm"></a> is still emitted.</p></div><div class="section" lang="en" xml:lang="en"><div class="titlepage"><div><div><h3 class="title"><a id="ch04lvl2sec18"></a>Emitting errors</h3></div></div></div><p>It is recommended that you emit an error on the <span>application</span><a id="id325913516" class="indexterm"></a> itself. This is useful for centralized error reporting or logging. This also helps to retain the default behavior of Koa for errors. Errors can be emitted using the <code class="literal">ctx.app.emit()</code> method:</p><pre class="programlisting"><span>app</span>.<span>use</span>(<span>async</span> (<span>ctx</span>, <span>next</span>) <span>=&gt;</span> {
  <span>try</span> {
    <span>await</span><span>next</span>();
  } <span>catch</span> (err) {
    <span>ctx</span>.<span>status</span><span>=</span><span>err</span>.<span>status</span><span>||</span><span>500</span>;
    <span>ctx</span>.<span>body</span><span>=</span><span>err</span>.<span>message</span>;
    <span>ctx</span>.<span>app</span>.<span>emit</span>(<span><span>'</span>error<span>'</span></span>, err, ctx);
  }
});</pre><p> </p></div><div class="section" lang="en" xml:lang="en"><div class="titlepage"><div><div><h3 class="title"><a id="ch04lvl2sec19"></a>Error event listener</h3></div></div></div><p><span class="strong"><strong>Error event listeners</strong></span> can be defined with <code class="literal">app.on('error').</code> They are particularly useful for centralized logging and error reporting. The error listeners receive all errors <span>that</span><a id="id326127917" class="indexterm"></a> are thrown in the middleware chain, except the ones that are caught and are neither rethrown or emitted using <code class="literal">app.emit()</code>. To define an error handler, refer to this code:</p><pre class="programlisting">app.on('error', err =&gt; {
  // log errors
  console.error("server error", err);
});</pre><p>If no event listener is defined, then <code class="literal">app.onerror</code> is used. This simply outputs the error to <code class="literal">stdout</code> unless <code class="literal">app.silent</code> is <code class="literal">true</code>, <code class="literal">err.status</code> is <code class="literal">404</code>, or <code class="literal">err.expose</code> is set to <code class="literal">true</code>.</p><p>If an error is thrown in the middleware chain and it is not possible to respond to the client, the context object is also passed to the event listener:</p><pre class="programlisting">app.on('error', (err, ctx) =&gt; {
  console.error("server error", err, ctx);
});</pre><p>It is important to note that these are user-level errors and are therefore safe to expose to the user (<code class="literal">err.expose</code> is set to <code class="literal">true</code>). This is usually not the case for all <span>error</span><a id="id326128151" class="indexterm"></a> messages, especially with 50x errors, where we do not want to show the client sensitive information from failures.</p></div></div>